baseURL = "https://alirus.ir/"
languageCode = "en-us"
title = "Alirus"
theme = "hugo-coder"
canonifyurls = "true"

[params]
    author = "Ali AslRousta"
    info = "Backend Developer | Go Enthusiast | Rust Lover"
    description = "A Developer's Personal Website"
    avatarurl = "images/avatar.jpg"
    keywords = "blog,developer,personal"
    math = "yes"
    hidecredits = "yes"
    hidecopyright = "yes"

# Social Links

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/aslrousta/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/aslrousta/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/aslrousta/"

[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 4
    url = "https://medium.com/@aslrousta"

# Menu Links

[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"

[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"